<?xml version="1.0"?>
<robot name="ackermann_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ===================== -->
  <!-- Real hardware values  -->
  <!-- ===================== -->

  <!-- Chassis -->
  <xacro:property name="chassis_length" value="0.27"/>
  <xacro:property name="chassis_width"  value="0.1205"/>
  <xacro:property name="chassis_height" value="0.002"/>
  <xacro:property name="chassis_mass"   value="0.126"/>

  <!-- Wheels -->
  <xacro:property name="wheel_radius" value="0.0375"/>
  <xacro:property name="wheel_width"  value="0.03"/>
  <xacro:property name="wheel_mass"   value="0.05"/>

  <!-- Geometry -->
  <xacro:property name="wheelbase" value="0.19"/>
  <xacro:property name="track" value="0.152"/> 


  <!-- Dual plate chassis -->
  <xacro:property name="plate_thickness" value="0.002"/>
  <xacro:property name="standoff_height" value="0.04"/>
  <xacro:property name="standoff_radius" value="0.004"/>

  <!-- Standoff positions -->
  <xacro:property name="standoff_x" value="${chassis_length/2 - 0.02}"/>
  <xacro:property name="standoff_y" value="${chassis_width/2 - 0.02}"/>

  <!-- Materials -->
  <material name="chassis_black">
    <color rgba="1.0 0.0 0.0 1"/>
  </material>

  <material name="wheel_black">
    <color rgba="0.05 0.05 0.05 1"/>
  </material>

  <!-- ===================== -->
  <!-- Base frame            -->
  <!-- ===================== -->
  <!-- Robot center reference -->
  <link name="base_link"/>

  <!-- ===================== -->
  <!-- Chassis               -->
  <!-- ===================== -->
  <link name="chassis_link">

    <inertial>
      <origin xyz="0 0 0"/>
      <mass value="${chassis_mass}"/>
      <inertia
        ixx="0.002" ixy="0" ixz="0"
        iyy="0.002" iyz="0"
        izz="0.002"/>
    </inertial>

    <!-- Bottom plate -->
    <visual>
      <origin xyz="${-chassis_length/100} ${-chassis_width/100} ${wheel_radius + plate_thickness/2}" rpy="0 0 1.5708"/>
      <geometry>
        <mesh filename="/home/mohana/robot_ws/install/ackermann_robot/share/ackermann_robot/meshes/chassis_visual.stl"
        scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="chassis_black"/>
    </visual>

    <!-- Top plate -->
    <visual>
      <origin xyz="${-chassis_length/100} ${-chassis_width/100} ${wheel_radius + plate_thickness + standoff_height + plate_thickness/2}" rpy="0 0 1.5708"/>
      <geometry>
        <mesh filename="/home/mohana/robot_ws/install/ackermann_robot/share/ackermann_robot/meshes/chassis_visual.stl"
        scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="chassis_black"/>
    </visual>


    <!-- Front left standoff -->
    <visual>
      <origin xyz="${standoff_x} ${standoff_y} ${wheel_radius + plate_thickness + standoff_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${standoff_radius}" length="${standoff_height}"/>
      </geometry>
      <material name="wheel_black"/>
    </visual>

    <!-- Front right -->
    <visual>
      <origin xyz="${standoff_x} -${standoff_y} ${wheel_radius + plate_thickness + standoff_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${standoff_radius}" length="${standoff_height}"/>
      </geometry>
      <material name="wheel_black"/>
    </visual>

    <!-- Rear left -->
    <visual>
      <origin xyz="-${standoff_x} ${standoff_y} ${wheel_radius + plate_thickness + standoff_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${standoff_radius}" length="${standoff_height}"/>
      </geometry>
      <material name="wheel_black"/>
    </visual>

    <!-- Rear right -->
    <visual>
      <origin xyz="-${standoff_x} -${standoff_y} ${wheel_radius + plate_thickness + standoff_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${standoff_radius}" length="${standoff_height}"/>
      </geometry>
      <material name="wheel_black"/>
    </visual>

    <!-- Collision: simple box for stable physics -->
    <collision>
      <origin xyz="0 0 ${chassis_height/2}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>

  </link>

  <!-- base â†’ chassis -->
  <joint name="base_to_chassis" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- ===================== -->
  <!-- Rear wheel macro      -->
  <!-- ===================== -->
  <xacro:macro name="rear_wheel" params="name x y">
    <!-- Wheel -->
    <link name="${name}_wheel_link">
      <inertial>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="3e-5" ixy="0" ixz="0"
          iyy="3e-5" iyz="0"
          izz="3e-5"/>
      </inertial>

      <visual>
        <origin rpy="1.5708 0 0"/>
        <geometry>
          <mesh filename="/home/mohana/robot_ws/install/ackermann_robot/share/ackermann_robot/meshes/wheel_visual.stl"
          scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="wheel_black"/>
      </visual>

      <collision>
        <origin rpy="1.5708 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
          <surface>
            <friction>
              <ode>
                <mu>0.5</mu>
                <mu2>1.0</mu2>
                <fdir1>0 0 1</fdir1>
              </ode>
              <bullet>
                <friction>0.5</friction>
                <friction2>1</friction2>
                <rolling_friction>0.1</rolling_friction>
              </bullet>
            </friction>
          </surface>
      </collision>
    </link>

    <!-- Gazebo friction for wheels -->
    <gazebo reference="${name}_wheel_link">
      <mu1>0.8</mu1>
      <mu2>0.8</mu2>
      <kp>1000000.0</kp>
      <kd>100.0</kd>
    </gazebo>

    <joint name="${name}_wheel_joint" type="revolute">
      <parent link="chassis_link"/>
      <child link="${name}_wheel_link"/>
      <origin xyz="${x} ${y} ${wheel_radius}"/>
      <axis xyz="0 1 0"/>
      <limit effort="10" velocity="10"/>
    </joint>
  </xacro:macro>

  <!-- ===================== -->
  <!-- Front steering macro  -->
  <!-- ===================== -->
  <xacro:macro name="front_steered_wheel" params="name x y">

    <!-- steering knuckle -->
    <link name="${name}_steer_link">
      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="0.01"/>
        <inertia
          ixx="1e-5" ixy="0" ixz="0"
          iyy="1e-5" iyz="0"
          izz="1e-5"/>
      </inertial>
    </link>

    <joint name="${name}_steer_joint" type="revolute">
      <parent link="chassis_link"/>
      <child link="${name}_steer_link"/>
      <origin xyz="${x} ${y} ${wheel_radius}"/>
      <axis xyz="0 0 1"/>
      <limit lower="-0.6" upper="0.6" effort="25" velocity="2"/>
    </joint>

    <!-- wheel -->
    <link name="${name}_wheel_link">
      <inertial>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="3e-5" ixy="0" ixz="0"
          iyy="3e-5" iyz="0"
          izz="3e-5"/>
      </inertial>

      <visual>
        <origin rpy="1.5708 0 0"/>
        <geometry>
          <!-- <cylinder radius="${wheel_radius}" length="${wheel_width}"/> -->
        <mesh filename="/home/mohana/robot_ws/install/ackermann_robot/share/ackermann_robot/meshes/wheel_visual.stl"
        scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="wheel_black"/>
      </visual>

      <collision>
        <origin rpy="1.5708 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
          <surface>
            <friction>
              <ode>
                <mu>0.5</mu>
                <mu2>1.0</mu2>
                <fdir1>0 0 1</fdir1>
              </ode>
              <bullet>
                <friction>0.5</friction>
                <friction2>1</friction2>
                <rolling_friction>0.1</rolling_friction>
              </bullet>
            </friction>
          </surface>
      </collision>
    </link>

    <!-- Gazebo friction for wheels -->
    <gazebo reference="${name}_wheel_link">
      <mu1>0.8</mu1>
      <mu2>0.8</mu2>
      <kp>1000000.0</kp>
      <kd>100.0</kd>
    </gazebo>

    <joint name="${name}_wheel_joint" type="revolute">
      <parent link="${name}_steer_link"/>
      <child link="${name}_wheel_link"/>
      <axis xyz="0 1 0"/>
      <limit effort="10" velocity="10"/>
    </joint>

  </xacro:macro>

  <!-- ===================== -->
  <!-- Wheel placement       -->
  <!-- ===================== -->

  <!-- Rear drive wheels -->
  <xacro:rear_wheel
      name="rear_left"
      x="-${wheelbase/2}"
      y="${track/2}"/>

  <xacro:rear_wheel
      name="rear_right"
      x="-${wheelbase/2}"
      y="-${track/2}"/>

  <!-- Front steering wheels -->
  <xacro:front_steered_wheel
      name="front_left"
      x="${wheelbase/2}"
      y="${track/2}"/>

  <xacro:front_steered_wheel
      name="front_right"
      x="${wheelbase/2}"
      y="-${track/2}"/>

  <!-- ===================== -->
  <!-- Gazebo plugins        -->
  <!-- ===================== -->
  
  <!-- Physics properties for chassis -->
  <!-- <gazebo reference="chassis_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <kp>1000000.0</kp>
    <kd>100.0</kd>
  </gazebo> -->
  
  <gazebo>
    <plugin
      filename="gz-sim-ackermann-steering-system"
      name="gz::sim::systems::AckermannSteering">
      
      <left_steering_joint>front_left_steer_joint</left_steering_joint>
      <right_steering_joint>front_right_steer_joint</right_steering_joint>
      
      <left_joint>front_left_wheel_joint</left_joint>
      <left_joint>rear_left_wheel_joint</left_joint>
      <right_joint>front_right_wheel_joint</right_joint>
      <right_joint>rear_right_wheel_joint</right_joint>

      <wheel_base>${wheelbase}</wheel_base>
      <wheel_separation>${track}</wheel_separation>
      <kingpin_width>${track}</kingpin_width>
      <wheel_radius>${wheel_radius}</wheel_radius>

      <steering_limit>0.5</steering_limit>
      <!-- <max_velocity>1.0</max_velocity>
      <max_acceleration>2.0</max_acceleration> -->
      
      <topic>/cmd_vel</topic>
      <odom_topic>/odometry</odom_topic>
      <tf_topic>/tf</tf_topic>
      <odom_publish_frequency>30</odom_publish_frequency>
    </plugin>
  </gazebo>
  <gazebo>
    <plugin
      filename="gz-sim-joint-state-publisher-system"
      name="gz::sim::systems::JointStatePublisher"/>
      <frame_id>base_link</frame_id>
  </gazebo>
</robot>
