# Clock bridge (Gazebo -> ROS)
- ros_topic_name: "/clock"
  gz_topic_name: "/world/multi_level_parking/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: "GZ_TO_ROS"

# Cmd velocity bridge (ROS -> Gazebo)
- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: "BIDIRECTIONAL"


# Odometry bridge (Gazebo -> ROS)
- ros_topic_name: "/odom"
  gz_topic_name: "/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: "GZ_TO_ROS"

# Ground Truth Odometry bridge (Gazebo -> ROS)
- ros_topic_name: "/ground_truth_odom"
  gz_topic_name: "/ground_truth_odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: "GZ_TO_ROS"

# # TF Bridge (Crucial for Odometry to work in RViz)
# - ros_topic_name: "/tf"
#   gz_topic_name: "/tf"
#   ros_type_name: "tf2_msgs/msg/TFMessage"
#   gz_type_name: "gz.msgs.Pose_V"
#   direction: "GZ_TO_ROS"

# Joint states bridge (Gazebo -> ROS)
- ros_topic_name: "/joint_states"
  gz_topic_name: "/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: "GZ_TO_ROS"

# IMU bridge (Gazebo -> ROS)
- ros_topic_name: "/imu"
  gz_topic_name: "/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: "GZ_TO_ROS"

# # Air Pressure bridge (Gazebo -> ROS)
# - ros_topic_name: "/air_pressure"
#   gz_topic_name: "/air_pressure"
#   ros_type_name: "sensor_msgs/msg/FluidPressure"
#   gz_type_name: "gz.msgs.FluidPressure"
#   direction: "GZ_TO_ROS"

# # GPS bridge (Gazebo -> ROS)
# - ros_topic_name: "/gps/fix"
#   gz_topic_name: "/gps/fix"
#   ros_type_name: "sensor_msgs/msg/NavSatFix"
#   gz_type_name: "gz.msgs.NavSat"
#   direction: "GZ_TO_ROS"

# Lidar bridge (Gazebo -> ROS)
- ros_topic_name: "/scan"
  gz_topic_name: "/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/scan/points"
  gz_topic_name: "/scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: "GZ_TO_ROS"

# Front Camera
- ros_topic_name: "/front_camera/image"
  gz_topic_name: "/front_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/front_camera/camera_info"
  gz_topic_name: "/front_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: "GZ_TO_ROS"

# Rear Camera
- ros_topic_name: "/rear_camera/image"
  gz_topic_name: "/rear_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/rear_camera/camera_info"
  gz_topic_name: "/rear_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: "GZ_TO_ROS"

# Left Camera
- ros_topic_name: "/left_camera/image"
  gz_topic_name: "/left_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/left_camera/camera_info"
  gz_topic_name: "/left_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: "GZ_TO_ROS"

# Right Camera
- ros_topic_name: "/right_camera/image"
  gz_topic_name: "/right_camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: "GZ_TO_ROS"

- ros_topic_name: "/right_camera/camera_info"
  gz_topic_name: "/right_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: "GZ_TO_ROS"

# # Front Lasers bridge (Gazebo -> ROS)
# - ros_topic_name: "/front_left_laser/scan"
#   gz_topic_name: "/front_left_laser/scan"
#   ros_type_name: "sensor_msgs/msg/LaserScan"
#   gz_type_name: "gz.msgs.LaserScan"
#   direction: "GZ_TO_ROS"

# - ros_topic_name: "/front_right_laser/scan"
#   gz_topic_name: "/front_right_laser/scan"
#   ros_type_name: "sensor_msgs/msg/LaserScan"
#   gz_type_name: "gz.msgs.LaserScan"
#   direction: "GZ_TO_ROS"

# # Sonars bridge (Gazebo -> ROS)
# - ros_topic_name: "/back_left_far_sonar/scan"
#   gz_topic_name: "/back_left_far_sonar/scan"
#   ros_type_name: "sensor_msgs/msg/LaserScan"
#   gz_type_name: "gz.msgs.LaserScan"
#   direction: "GZ_TO_ROS"

# - ros_topic_name: "/back_left_middle_sonar/scan"
#   gz_topic_name: "/back_left_middle_sonar/scan"
#   ros_type_name: "sensor_msgs/msg/LaserScan"
#   gz_type_name: "gz.msgs.LaserScan"
#   direction: "GZ_TO_ROS"

# - ros_topic_name: "/back_right_far_sonar/scan"
#   gz_topic_name: "/back_right_far_sonar/scan"
#   ros_type_name: "sensor_msgs/msg/LaserScan"
#   gz_type_name: "gz.msgs.LaserScan"
#   direction: "GZ_TO_ROS"

# - ros_topic_name: "/back_right_middle_sonar/scan"
#   gz_topic_name: "/back_right_middle_sonar/scan"
#   ros_type_name: "sensor_msgs/msg/LaserScan"
#   gz_type_name: "gz.msgs.LaserScan"
#   direction: "GZ_TO_ROS"

# - ros_topic_name: "/front_left_far_sonar/scan"
#   gz_topic_name: "/front_left_far_sonar/scan"
#   ros_type_name: "sensor_msgs/msg/LaserScan"
#   gz_type_name: "gz.msgs.LaserScan"
#   direction: "GZ_TO_ROS"

# - ros_topic_name: "/front_left_middle_sonar/scan"
#   gz_topic_name: "/front_left_middle_sonar/scan"
#   ros_type_name: "sensor_msgs/msg/LaserScan"
#   gz_type_name: "gz.msgs.LaserScan"
#   direction: "GZ_TO_ROS"

# - ros_topic_name: "/front_right_far_sonar/scan"
#   gz_topic_name: "/front_right_far_sonar/scan"
#   ros_type_name: "sensor_msgs/msg/LaserScan"
#   gz_type_name: "gz.msgs.LaserScan"
#   direction: "GZ_TO_ROS"

# - ros_topic_name: "/front_right_middle_sonar/scan"
#   gz_topic_name: "/front_right_middle_sonar/scan"
#   ros_type_name: "sensor_msgs/msg/LaserScan"
#   gz_type_name: "gz.msgs.LaserScan"
#   direction: "GZ_TO_ROS"

# # Environment Reference Barometer (Ground Station -> ROS)
# - ros_topic_name: "/env/reference_pressure"
#   gz_topic_name: "/env/reference_pressure"
#   ros_type_name: "sensor_msgs/msg/FluidPressure"
#   gz_type_name: "gz.msgs.FluidPressure"
#   direction: "GZ_TO_ROS"
