<?xml version="1.0"?>
<robot name="ackermann_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- ===================== -->
  <!-- Real hardware values  -->
  <!-- ===================== -->

  <!-- Chassis -->
  <xacro:property name="chassis_length" value="0.27"/>
  <xacro:property name="chassis_width"  value="0.1205"/>
  <xacro:property name="chassis_height" value="0.00"/>
  <xacro:property name="chassis_mass"   value="0.13442"/>

  <!-- Wheels -->
  <xacro:property name="wheel_radius" value="0.036"/>
  <xacro:property name="wheel_width"  value="0.03"/>
  <xacro:property name="wheel_mass"   value="0.0677"/>

  <!-- Geometry -->
  <xacro:property name="wheelbase" value="0.205"/>
  <xacro:property name="track" value="0.152"/> 


  <!-- Dual plate chassis -->
  <xacro:property name="plate_thickness" value="0.002"/>
  <xacro:property name="standoff_height" value="0.04"/>
  <xacro:property name="standoff_radius" value="0.004"/>

  <!-- Standoff positions -->
  <xacro:property name="standoff_x" value="${chassis_length/2 - 0.02}"/>
  <xacro:property name="standoff_y" value="${chassis_width/2 - 0.02}"/>

  <!-- Materials -->
  <material name="chassis_red">
    <color rgba="1.0 0.0 0.0 1"/>
  </material>

  <material name="wheel_black">
    <color rgba="0.05 0.05 0.05 1"/>
  </material>

  <!-- ===================== -->
  <!-- Base frame            -->
  <!-- ===================== -->
  <!-- Robot center reference -->
  <link name="base_link"/>

  <!-- ===================== -->
  <!-- Chassis               -->
  <!-- ===================== -->
  <link name="chassis_link">
    <inertial>
      <origin xyz="0 0 ${chassis_height/2}"/>
      <mass value="${chassis_mass}"/>
      <inertia
        ixx="1.50903123e-04" ixy="4.70052075e-08" ixz="6.59784866e-15"
        iyy="8.14177826e-04" iyz="1.01460270e-15"
        izz="9.64991335e-04"/>
      </inertial>

    <!-- Bottom plate -->
    <visual>
      <origin xyz="0 0 ${wheel_radius + plate_thickness/2}" rpy="0 0 0"/>
      <geometry>
        <mesh filename="/home/mohana/robot_ws/src/ackermann_robot/meshes/chassis_visual.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="chassis_red"/>
    </visual>

    <!-- Top plate -->
    <visual>
      <origin xyz="0 0 ${wheel_radius + plate_thickness/2 + plate_thickness + standoff_height}" rpy="0 0 0"/>
      <geometry>
        <mesh filename="/home/mohana/robot_ws/src/ackermann_robot/meshes/chassis_visual.stl" scale="0.001 0.001 0.001"></mesh>
      </geometry>
      <material name="chassis_red"/>
    </visual>


    <!-- Front left standoff -->
    <visual>
      <origin xyz="${standoff_x} ${standoff_y} ${wheel_radius + plate_thickness + standoff_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${standoff_radius}" length="${standoff_height}"/>
      </geometry>
      <material name="wheel_black"/>
    </visual>

    <!-- Front right -->
    <visual>
      <origin xyz="${standoff_x} -${standoff_y} ${wheel_radius + plate_thickness + standoff_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${standoff_radius}" length="${standoff_height}"/>
      </geometry>
      <material name="wheel_black"/>
    </visual>

    <!-- Rear left -->
    <visual>
      <origin xyz="-${standoff_x} ${standoff_y} ${wheel_radius + plate_thickness + standoff_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${standoff_radius}" length="${standoff_height}"/>
      </geometry>
      <material name="wheel_black"/>
    </visual>

    <!-- Rear right -->
    <visual>
      <origin xyz="-${standoff_x} -${standoff_y} ${wheel_radius + plate_thickness + standoff_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${standoff_radius}" length="${standoff_height}"/>
      </geometry>
      <material name="wheel_black"/>
    </visual>

    <!-- Collision: simple box for stable physics -->
    <collision>
      <origin xyz="0 0 ${chassis_height/2}"/>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
      </geometry>
    </collision>

  </link>

  <!-- base â†’ chassis -->
  <joint name="base_to_chassis" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- ===================== -->
  <!-- Rear wheel macro      -->
  <!-- ===================== -->
  <xacro:macro name="rear_wheel" params="name x y">
    <!-- Wheel -->
    <link name="${name}_wheel_link">
      <inertial>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="3.21561728e-05" ixy="1.40375656e-15" ixz="-3.63476706e-15"
          iyy="5.65938896e-05" iyz="-1.35718707e-16"
          izz="3.21561633e-05"/>
      </inertial>
      <visual>
        <origin rpy=" 0 0 3.1412"/>
        <geometry>
          <mesh filename="/home/mohana/robot_ws/src/ackermann_robot/meshes/${name}_wheel.stl"
          scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="wheel_black"/>
      </visual>

      <collision>
        <origin rpy="1.5708 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <!-- Gazebo friction for wheels -->
    <!-- <gazebo reference="${name}_wheel_link">
      <mu1>0.8</mu1>
      <mu2>0.8</mu2>
    </gazebo> -->

    <joint name="${name}_wheel_joint" type="continuous">
      <parent link="chassis_link"/>
      <child link="${name}_wheel_link"/>
      <origin xyz="${x} ${y} ${wheel_radius}"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- ===================== -->
  <!-- Front steering macro  -->
  <!-- ===================== -->
  <xacro:macro name="front_steered_wheel" params="name x y">

    <!-- steering knuckle -->
    <link name="${name}_steer_link">
      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="0.01"/>
        <inertia
          ixx="1e-5" ixy="0" ixz="0"
          iyy="1e-5" iyz="0"
          izz="1e-5"/>
      </inertial>
    </link>

    <joint name="${name}_steer_joint" type="revolute">
      <parent link="chassis_link"/>
      <child link="${name}_steer_link"/>
      <origin xyz="${x} ${y} ${wheel_radius}"/>
      <axis xyz="0 0 1"/>
      <limit lower="-0.6" upper="0.6" effort="10" velocity="2"/>
    </joint>

    <!-- wheel -->
    <link name="${name}_wheel_link">
      <inertial>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="3e-5" ixy="0" ixz="0"
          iyy="3e-5" iyz="0"
          izz="3e-5"/>
      </inertial>

      <visual>
        <origin rpy="0 0 3.1412"/>
        <geometry>
          <!-- <cylinder radius="${wheel_radius}" length="${wheel_width}"/> -->
        <mesh filename="/home/mohana/robot_ws/src/ackermann_robot/meshes/${name}_wheel.stl"
        scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="wheel_black"/>
      </visual>

      <collision>
        <origin rpy="1.5708 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <!-- Gazebo friction for wheels -->
    <!-- <gazebo reference="${name}_wheel_link">
      <mu1>1.0</mu1>
      <mu2>0.8</mu2>
    </gazebo> -->

    <joint name="${name}_wheel_joint" type="continuous">
      <parent link="${name}_steer_link"/>
      <child link="${name}_wheel_link"/>
      <axis xyz="0 1 0"/>
    </joint>

  </xacro:macro>

  <!-- ===================== -->
  <!-- Wheel placement       -->
  <!-- ===================== -->

  <!-- Rear drive wheels -->
  <xacro:rear_wheel
      name="rear_left"
      x="-${wheelbase/2}"
      y="${track/2}"/>

  <xacro:rear_wheel
      name="rear_right"
      x="-${wheelbase/2}"
      y="-${track/2}"/>

  <!-- Front steering wheels -->
  <xacro:front_steered_wheel
      name="front_left"
      x="${wheelbase/2}"
      y="${track/2}"/>

  <xacro:front_steered_wheel
      name="front_right"
      x="${wheelbase/2}"
      y="-${track/2}"/>

  <!-- ===================== -->
  <!-- Gazebo plugins        -->
  <!-- ===================== -->
  
  <!-- Physics properties for chassis -->
  <!-- <gazebo reference="chassis_link">
    <mu1>0.8</mu1>
    <mu2>0.8</mu2>
  </gazebo> -->
  
  <gazebo>
    <plugin
      filename="gz-sim-ackermann-steering-system"
      name="gz::sim::systems::AckermannSteering">
      
      <left_steering_joint>front_left_steer_joint</left_steering_joint>
      <right_steering_joint>front_right_steer_joint</right_steering_joint>
      
      <left_joint>front_left_wheel_joint</left_joint>
      <left_joint>rear_left_wheel_joint</left_joint>
      <right_joint>front_right_wheel_joint</right_joint>
      <right_joint>rear_right_wheel_joint</right_joint>

      <wheel_base>${wheelbase}</wheel_base>
      <wheel_separation>${track}</wheel_separation>
      <kingpin_width>${track}</kingpin_width>
      <wheel_radius>${wheel_radius}</wheel_radius>

      <steering_limit>0.5</steering_limit> 
      <topic>/cmd_vel</topic>
      <odom_topic>/odometry</odom_topic>
      <tf_topic>/tf</tf_topic>
      <odom_publish_frequency>30</odom_publish_frequency>
    </plugin>
  </gazebo>
  <gazebo>
    <plugin
      filename="gz-sim-joint-state-publisher-system"
      name="gz::sim::systems::JointStatePublisher"/>
  </gazebo>
</robot>
